// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeletedUser struct {
	ID          pgtype.UUID
	Firstname   string
	Lastname    string
	Email       string
	MemberSince pgtype.Timestamptz
	Password    string
}

type IssuedRefreshToken struct {
	Sub pgtype.UUID
	Jti pgtype.UUID
	Exp pgtype.Timestamptz
	Iat pgtype.Timestamptz
}

type IssuedRefreshTokensBlacklist struct {
	Jti pgtype.UUID
	Exp pgtype.Timestamptz
}

type StripeInfo struct {
	UserID                pgtype.UUID
	StripeCustomerID      string
	StripeSubscriptionID  string
	StripePaymentMethodID string
	CreatedAt             pgtype.Timestamptz
}

type UnverifiedUser struct {
	ID               pgtype.UUID
	Email            string
	VerificationCode string
}

type User struct {
	ID          pgtype.UUID
	Firstname   string
	Lastname    string
	Email       string
	MemberSince pgtype.Timestamptz
	Password    string
}
