// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertNewUser = `-- name: InsertNewUser :exec
INSERT INTO users
(id, firstname, lastname, email, password)
VALUES ($1, $2, $3, $4, $5)
`

type InsertNewUserParams struct {
	ID        pgtype.UUID
	Firstname string
	Lastname  string
	Email     string
	Password  string
}

func (q *Queries) InsertNewUser(ctx context.Context, arg InsertNewUserParams) error {
	_, err := q.db.Exec(ctx, insertNewUser,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO issued_refresh_tokens 
(sub, jti, exp) 
VALUES ($1, $2, $3)
`

type InsertRefreshTokenParams struct {
	Sub pgtype.UUID
	Jti pgtype.UUID
	Exp pgtype.Timestamptz
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.Sub, arg.Jti, arg.Exp)
	return err
}

const insertStripeInfo = `-- name: InsertStripeInfo :exec
INSERT INTO stripe_info 
(user_id, stripe_customer_id, stripe_subscription_id, stripe_payment_method_id)
VALUES ($1, $2, $3, $4)
`

type InsertStripeInfoParams struct {
	UserID                pgtype.UUID
	StripeCustomerID      string
	StripeSubscriptionID  string
	StripePaymentMethodID string
}

func (q *Queries) InsertStripeInfo(ctx context.Context, arg InsertStripeInfoParams) error {
	_, err := q.db.Exec(ctx, insertStripeInfo,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.StripePaymentMethodID,
	)
	return err
}

const insertUnverifiedUser = `-- name: InsertUnverifiedUser :exec
INSERT INTO unverified_users
(id, email, verification_code)
VALUES ($1, $2, $3)
`

type InsertUnverifiedUserParams struct {
	ID               pgtype.UUID
	Email            string
	VerificationCode string
}

func (q *Queries) InsertUnverifiedUser(ctx context.Context, arg InsertUnverifiedUserParams) error {
	_, err := q.db.Exec(ctx, insertUnverifiedUser, arg.ID, arg.Email, arg.VerificationCode)
	return err
}
